# Generated by Django 3.1.5 on 2021-06-07 08:50

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media/image')),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
