# Generated by Django 3.1.5 on 2021-10-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211016_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likePost',
        ),
    ]
